### PR TITLE
Title block

### LINKED ISSUE #11: Title block
Add support for a block that updates an Axes title.

Likely supporting 2 data formats:

1. list of strings
2. string with format specifiers, list of stuff to interpolate the string with.

### PR DESCRIPTION
**Pull request by TomNicholas**
Closes #11.

I wanted to understand how this library works a bit better so I had a go at writing a new block - the title block.

I wrote it using test-driven development so there are some unit tests included too.

I also grouped your existing comparison tests into a class.

I tried to use args and kwargs in such a way that any type of format string can be passed, and any kwargs intended for the call to `matplotlib.pyplot.ax.set_title()` are specified as a separate dictionary.

Let me know what you think.

### CODE REVIEW

**Comment by t-makaro** [comment]
At first pass, this looks great! I'm not sure that we should separate out ```mpl_kwargs``` for API consistency. I think it would be better to explicitly have a "replacements" kwarg. Maybe ```replacements-None```, and just handle the cases of None, sequence, and dictionary. It may be worth looking into figuring out how to do multiple replacements for each time step. Example: ```"%s = %d"``` where both %s and %d are replaced at each step. I'll take another look at this later. May just merge and iterate. 

Also, I'm not sure why circleCI hasn't run the tests. The TestTitleBlock may fail on circleCI due to a freetype issue. (text renders ever so slightly differently for different versions of freetype).

**Comment by t-makaro** [comment]
This is a new block so backwards compatibility is not an issue. There is no need to add the check for the ```axis``` kwarg.

**Comment by TomNicholas** [comment]
> At first pass, this looks great!

Glad you approve!

> I think it would be better to explicitly have a "replacements" kwarg.

So the whole point of my approach was that the title block would allow you to enter a string as if you were just writing a normal format string. Having an explicit `replacements` kwarg would stop that.

> I'm not sure that we should separate out mpl_kwargs for API consistency.

I did consider another way of writing this which would avoid an `mpl_kwargs` argument: you could filter all the kwargs by selecting those whose keys are in `fieldnames`, then assume any remaining should be passed on to matplotlib.

> It may be worth looking into figuring out how to do multiple replacements for each time step.

Unless I'm understanding you wrong then it already does this (and there's a corresponding unit test). e.g.
```python
Title("{person} = {id}", person=['Alice', 'Bob'], id=[1, 2])
```
will create a title block where both person and id change on every time step.

> no need to add the check for the axis kwarg.

I'll remove that now then!

**Comment by t-makaro** [comment]
Those are good points. Definitely an interesting idea to have it behave like a format string. I like it (I was going to implement a title block using old school string interpolation %).

I think I need to think about ```mpl_kwargs```. Maybe it would be better to change the other blocks API, but in general I like blocks to behave like the mpl API. So, leftover kwargs for a block get passed into the mpl function that the block wraps. Hold off on changing this.

I don't think we should format all of the titles beforehand. It uses more memory. A user could pre-format the text if they want. I think the purpose of allowing format strings and replacements is to avoid this increase in memory. Strings should be formatted before updating.

**Comment by TomNicholas** [comment]
> So, leftover kwargs for a block get passed into the mpl function that the block wraps.

That's precisely what I'm suggesting I change it to! :grin:

> I don't think we should format all of the titles beforehand. It uses more memory. 

Really? I have very little idea of how this works but all we're doing is creating a list of maybe ~100 strings, surely the memory use of that will always be tiny compared to what's used for the actual image?

**Comment by t-makaro** [comment]
> That's precisely what I'm suggesting I change it to! 

The only probably is if the call to title (or it's call to text) uses a kwarg that the user has placed in the format string. This would make using the kwarg to title impossible.

> creating a list of maybe ~100 strings, surely the memory use of that will always be tiny compared to what's used for the actual image?

For most use cases probably. Though strings would likely take more memory than plotting lines or scatter plots. It should be simple to take the frame number in the update method and update as format the string as needed. Though this is not a big deal, and can be left for a future change.

**Comment by TomNicholas** [comment]
> The only probably is if the call to title (or it's call to text) uses a kwarg that the user has placed in the format string. This would make using the kwarg to title impossible.

That's why I chose not to do it that way originally. But it's not possible to have complete freedom in both the format string and also pass arbitrary kwargs down to the matplotlib call, the only way to completely avoid collisions is to store one of the sets of kwargs in a separate dictionary. Now I think that the best compromise would be to do the filter method we're suggesting here, and throw an error if the user creates a collision.

>  It should be simple to take the frame number in the update method and update as format the string as needed. 

I still don't really understand how the strings are likely to take up much space, but I agree that changing the update method so that the string is formatted only when needed would be easy, and I would be happy to change that.

**Comment by t-makaro** [comment]
I set CircleCI to "Build Forked Pull Requests", so if you push another commit, it should run the tests on CircleCI. You could add a link to the Title Block under ```docs/source/api.rst```. Maybe under the auto-summary for "advanced blocks", or under a new auto-summary for "Graph Control Blocks" (I can't think of anything better to name it).

**Pull request merged**
